Repository process-analytics/bpmn-visualization-addons, pull requests merged in 2023-09, with the labels that each got.

#104 chore: configure Jest to let write tests in Typescript
  .github/dependabot.yml
  package-lock.json
  packages/addons/jest.config.js
  packages/addons/package.json
  packages/addons/test/plugins-support.test.ts
  packages/addons/tsconfig.json
  packages/addons/tsconfig.test.json
  tsconfig.eslint.json
Labels: chore, dependencies

#109 chore: use bpmn-visualization 0.39.0 as the minimum version required
  .github/actions/build-setup/action.yml
  bin/patch.bpmn-visualization.js
  package-lock.json
  package.json
  packages/addons/package.json
  packages/demo/package.json
  patches/bpmn-visualization_0.38.1.package.json
Labels: chore

#110 refactor(demo): move assets to a dedicated sub-folder
  packages/demo/index.html
  packages/demo/src/assets/diagram.bpmn
  packages/demo/src/assets/index.css
  packages/demo/src/assets/path-resolver.css
  packages/demo/src/overlays.ts
  packages/demo/src/path-resolver.ts
Labels: refactoring

#106 feat!: use generic type when getting a plugin
  packages/addons/README.md
  packages/addons/src/plugins-support.ts
  packages/addons/test/plugins-support.test.ts
  packages/addons/test/plugins/overlays.test.ts
  packages/demo/src/overlays.ts
Labels: enhancement

#112 test: move test files to a dedicated sub-folder
  .github/workflows/build.yml
  packages/addons/test/spec/plugins-support.test.ts
  packages/addons/test/spec/plugins/overlays.test.ts
Labels: chore

#115 feat: improve the robustness of BPMN elements utilities
  packages/addons/src/bpmn-elements.ts
  packages/addons/test/fixtures/bpmn/search-elements.bpmn
  packages/addons/test/spec/bpmn-elements.test.ts
Labels: enhancement

#108 chore(eslint): add ESLint configuration for Jest
  package-lock.json
  packages/addons/package.json
  packages/addons/test/.eslintrc.cjs
Labels: chore

#118 feat: allow to find flows when searching by name
  packages/addons/src/bpmn-elements.ts
  packages/addons/test/fixtures/bpmn/search-elements.bpmn
  packages/addons/test/spec/bpmn-elements.test.ts
Labels: enhancement

#119 feat: improve the robustness of `PathResolver`
  packages/addons/src/paths.ts
  packages/addons/test/fixtures/bpmn/paths/simple-with-wrong-incoming-and-outgoing.bpmn
  packages/addons/test/fixtures/bpmn/paths/simple.bpmn
  packages/addons/test/spec/paths.test.ts
Labels: enhancement

#120 feat: detect message flows with `PathResolver`
  packages/addons/test/fixtures/bpmn/paths/pools-and-message-flows.bpmn
  packages/addons/test/spec/paths.test.ts
Labels: enhancement

#123 feat: expose bpmn-visualization methods in OverlaysPlugin
  packages/addons/src/plugins/overlays.ts
  packages/addons/test/fixtures/bpmn/paths/pools-and-message-flows.bpmn
  packages/addons/test/fixtures/bpmn/paths/simple-with-wrong-incoming-and-outgoing.bpmn
  packages/addons/test/fixtures/bpmn/paths/simple.bpmn
  packages/addons/test/spec/plugins/overlays.test.ts
  packages/demo/src/overlays.ts
Labels: enhancement
